
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel RC
 */
public class Ingreso extends javax.swing.JFrame {

    String usuario = "danielrc";
    String contrasena = "living";

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        principal = new javax.swing.JTabbedPane();
        tp_ingreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        tf_contraseña = new javax.swing.JTextField();
        tp_registro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nuevousuario = new javax.swing.JTextField();
        tf_nuevacontra = new javax.swing.JTextField();
        tf_nuevotel = new javax.swing.JTextField();
        rb_fantasia = new javax.swing.JRadioButton();
        rb_romance = new javax.swing.JRadioButton();
        rb_accion = new javax.swing.JRadioButton();
        rb_historia = new javax.swing.JRadioButton();
        b_registrarse = new javax.swing.JButton();
        tp_administar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        l_titulo = new javax.swing.JTextField();
        l_descripcion = new javax.swing.JTextField();
        l_puntaje = new javax.swing.JTextField();
        l_copias = new javax.swing.JTextField();
        l_genero = new javax.swing.JTextField();
        l_valor = new javax.swing.JTextField();
        l_edicion = new javax.swing.JTextField();
        l_autor = new javax.swing.JTextField();
        l_año = new javax.swing.JTextField();
        libroregistrar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        l_titulo1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        l_descripcion1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        l_puntaje1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        l_copias1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        l_genero1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        l_valor1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        l_edicion1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        l_autor1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        l_año1 = new javax.swing.JTextField();
        libroregistrar1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        l_titulo2 = new javax.swing.JTextField();
        tp_libros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_libros = new javax.swing.JTable();
        jb_buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tf_eliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("USUARIO");

        jLabel3.setText("CONTRASEÑA");

        Entrar.setText("ENTRAR");
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarMouseClicked(evt);
            }
        });
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        tf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_contraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tp_ingresoLayout = new javax.swing.GroupLayout(tp_ingreso);
        tp_ingreso.setLayout(tp_ingresoLayout);
        tp_ingresoLayout.setHorizontalGroup(
            tp_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_ingresoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tp_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(tp_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Entrar)
                    .addComponent(tf_usuario)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        tp_ingresoLayout.setVerticalGroup(
            tp_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_ingresoLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(tp_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tp_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_ingresoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(tp_ingresoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(Entrar)
                .addGap(27, 27, 27))
        );

        principal.addTab("Ingreso", tp_ingreso);

        jLabel1.setText("Usuario");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Telefono");

        jLabel6.setText("Genero favorito");

        buttonGroup1.add(rb_fantasia);
        rb_fantasia.setText("Fantasia");

        buttonGroup1.add(rb_romance);
        rb_romance.setText("Romance");
        rb_romance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_romanceActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_accion);
        rb_accion.setText("Accion");

        buttonGroup1.add(rb_historia);
        rb_historia.setSelected(true);
        rb_historia.setText("Historia");

        b_registrarse.setText("Registrarse");
        b_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_registrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tp_registroLayout = new javax.swing.GroupLayout(tp_registro);
        tp_registro.setLayout(tp_registroLayout);
        tp_registroLayout.setHorizontalGroup(
            tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_registroLayout.createSequentialGroup()
                .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_registroLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_registroLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tf_nuevacontra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_registroLayout.createSequentialGroup()
                                .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_nuevousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_registroLayout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(rb_fantasia)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rb_romance)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rb_accion)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_registroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_nuevotel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_historia))))
                    .addGroup(tp_registroLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(b_registrarse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tp_registroLayout.setVerticalGroup(
            tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_registroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nuevousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nuevacontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nuevotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(tp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb_fantasia)
                    .addComponent(rb_romance)
                    .addComponent(rb_accion)
                    .addComponent(rb_historia))
                .addGap(32, 32, 32)
                .addComponent(b_registrarse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principal.addTab("Registro", tp_registro);

        jLabel8.setText("Titulo");

        jLabel9.setText("Descripcion");

        jLabel10.setText("puntaje");

        jLabel11.setText("Copias disponibles");

        jLabel12.setText("Genero");

        jLabel13.setText("Valor");

        jLabel14.setText("Edicion");

        jLabel15.setText("Autor");

        jLabel16.setText("Año Publicacion");

        libroregistrar.setText("Agregar");
        libroregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libroregistrarMouseClicked(evt);
            }
        });
        libroregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroregistrarActionPerformed(evt);
            }
        });

        jLabel17.setText("Titulo");

        l_titulo1.setText("(Ingrese aqui el titulo del libro a modificar)");
        l_titulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_titulo1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Descripcion");

        jLabel19.setText("puntaje");

        jLabel20.setText("Copias disponibles");

        jLabel21.setText("Genero");

        jLabel22.setText("Valor");

        jLabel23.setText("Edicion");

        jLabel24.setText("Autor");

        jLabel25.setText("Año Publicacion");

        libroregistrar1.setText("GUARDAR CAMBIO");
        libroregistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libroregistrar1MouseClicked(evt);
            }
        });
        libroregistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroregistrar1ActionPerformed(evt);
            }
        });

        jLabel26.setText("-----------------------------MODIFICAR---------------------------------");

        javax.swing.GroupLayout tp_administarLayout = new javax.swing.GroupLayout(tp_administar);
        tp_administar.setLayout(tp_administarLayout);
        tp_administarLayout.setHorizontalGroup(
            tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_administarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_administarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(l_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_administarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jLabel26)
                                .addGap(32, 32, 32)))
                        .addComponent(libroregistrar)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_administarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_descripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_administarLayout.createSequentialGroup()
                                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l_puntaje, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(l_copias))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(tp_administarLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(l_edicion))
                                .addGroup(tp_administarLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(l_autor))
                                .addGroup(tp_administarLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(l_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tp_administarLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(l_año, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))))
            .addGroup(tp_administarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8)
                .addComponent(l_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tp_administarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(l_titulo2))
                    .addComponent(l_descripcion1)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_puntaje1)
                            .addComponent(l_copias1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(libroregistrar1)
                        .addGap(28, 28, 28)))
                .addGap(18, 18, 18)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tp_administarLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(l_edicion1))
                        .addGroup(tp_administarLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(l_autor1))
                        .addGroup(tp_administarLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(l_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(l_año1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        tp_administarLayout.setVerticalGroup(
            tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_administarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(l_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(l_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(l_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(l_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(l_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(l_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(libroregistrar))
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(l_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addGap(11, 11, 11)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(l_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23)
                    .addComponent(l_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_edicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(l_puntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(l_autor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_administarLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(1, 1, 1)
                        .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(l_año1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_copias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(libroregistrar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tp_administarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(l_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        principal.addTab("Administrar", tp_administar);

        jt_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Genero", "Puntaje", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_libros);

        jb_buscar.setText("Buscar...");
        jb_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarMouseClicked(evt);
            }
        });
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jLabel7.setText("TITULO:");

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        tf_eliminar.setText("Ingrese titulo a eliminar aqui");

        javax.swing.GroupLayout tp_librosLayout = new javax.swing.GroupLayout(tp_libros);
        tp_libros.setLayout(tp_librosLayout);
        tp_librosLayout.setHorizontalGroup(
            tp_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_librosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tp_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_librosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(tp_librosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jb_buscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_librosLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(tf_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(232, 232, 232))
        );
        tp_librosLayout.setVerticalGroup(
            tp_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_librosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(tp_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jLabel7)
                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tp_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tf_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        principal.addTab("Lista libros", tp_libros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principal)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseClicked
        tp_administar.setEnabled(false);
        if (usuario.equals(tf_usuario.getText()) && contrasena.equals(tf_contraseña.getText())) {
            tp_administar.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Bienvenido Administrador");

        } else {
            for (int i = 0; i < usuarios.size() + 1; i++) {
                if (usuarios.get(i).getUsuario().equals(tf_usuario.getText()) && usuarios.get(i).getContraseña().equals(tf_contraseña.getText())) {
                    JOptionPane.showMessageDialog(this, "Usted ha ingresado con exito");

                }
            }

        }
        {

        }
    }//GEN-LAST:event_EntrarMouseClicked

    private void rb_romanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_romanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_romanceActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarActionPerformed

    private void tf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_contraseñaActionPerformed

    private void b_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_registrarseMouseClicked
        JOptionPane.showMessageDialog(this, "Usted ha sido registrado con exito");
        String genero = "";
        if (rb_fantasia.isSelected()) {
            genero = "Fantasia";
        } else if (rb_romance.isSelected()) {
            genero = "Romance";
        } else if (rb_accion.isSelected()) {
            genero = "Accion";
        } else if (rb_historia.isSelected()) {
            genero = "Historia";
        }
        usuarios.add(new Usuario(tf_nuevousuario.getText(), tf_nuevacontra.getText(), tf_nuevotel.getText(), genero));
    }//GEN-LAST:event_b_registrarseMouseClicked

    private void jb_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarMouseClicked

        for (int i = 0; i < libros.size(); i++) {
            if (tf_titulo.getText().equals(libros.get(i).getTitulo())) {
                Object[] newrow = {
                    libros.get(i).getTitulo(), libros.get(i).getAutor(), libros.get(i).getGenero(), libros.get(i).getPuntaje(),libros.get(i).getValor()};
                        DefaultTableModel modelo = (DefaultTableModel) jt_libros.getModel();
            modelo.addRow(newrow);
            jt_libros.setModel(modelo);
            } else if (tf_titulo.getText().equals("")) {
                Object[] newrow = {
                    libros.get(i).getTitulo(), libros.get(i).getAutor(), libros.get(i).getGenero(), libros.get(i).getPuntaje(),libros.get(i).getValor()};
                 DefaultTableModel modelo = (DefaultTableModel) jt_libros.getModel();
            modelo.addRow(newrow);
            jt_libros.setModel(modelo);
            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra en disposicion");
            }
        }
    }//GEN-LAST:event_jb_buscarMouseClicked

    private void libroregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroregistrarMouseClicked

        libros.add(new Libros(l_titulo.getText(), l_descripcion.getText(), l_puntaje.getText(), l_copias.getText(), l_genero.getText(), l_valor.getText(), l_edicion.getText(), l_autor.getText(), l_año.getText()));
    }//GEN-LAST:event_libroregistrarMouseClicked

    private void libroregistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroregistrar1MouseClicked
        for (int i = 0; i < libros.size(); i++) {
            if (l_titulo1.getText().equals(libros.get(i).getTitulo())) {
                libros.get(i).setTitulo(l_titulo2.getText());
                libros.get(i).setAutor(l_autor1.getText());
                libros.get(i).setGenero(l_genero1.getText());
                libros.get(i).setPuntaje(l_puntaje1.getText());
            }
        }
    }//GEN-LAST:event_libroregistrar1MouseClicked

    private void l_titulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_titulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_titulo1ActionPerformed

    private void libroregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroregistrarActionPerformed
        libroregistrar.setEnabled(false);
        if (usuario.equals(tf_usuario.getText()) && contrasena.equals(tf_contraseña.getText())) {
            libroregistrar.setEnabled(true);
        }
    }//GEN-LAST:event_libroregistrarActionPerformed

    private void libroregistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroregistrar1ActionPerformed
        libroregistrar1.setEnabled(false);
        if (usuario.equals(tf_usuario.getText()) && contrasena.equals(tf_contraseña.getText())) {
            libroregistrar1.setEnabled(true);
        }
    }//GEN-LAST:event_libroregistrar1ActionPerformed

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jt_libros.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jt_libros.getModel();
            modelo.removeRow(jt_libros.getSelectedRow());
            jt_libros.setModel(modelo);
        }
        for (int i = 0; i < libros.size(); i++) {
            if (tf_eliminar.getText().equals(libros.get(i).getTitulo())) {
                libros.remove(i);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JButton b_registrarse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JTable jt_libros;
    private javax.swing.JTextField l_autor;
    private javax.swing.JTextField l_autor1;
    private javax.swing.JTextField l_año;
    private javax.swing.JTextField l_año1;
    private javax.swing.JTextField l_copias;
    private javax.swing.JTextField l_copias1;
    private javax.swing.JTextField l_descripcion;
    private javax.swing.JTextField l_descripcion1;
    private javax.swing.JTextField l_edicion;
    private javax.swing.JTextField l_edicion1;
    private javax.swing.JTextField l_genero;
    private javax.swing.JTextField l_genero1;
    private javax.swing.JTextField l_puntaje;
    private javax.swing.JTextField l_puntaje1;
    private javax.swing.JTextField l_titulo;
    private javax.swing.JTextField l_titulo1;
    private javax.swing.JTextField l_titulo2;
    private javax.swing.JTextField l_valor;
    private javax.swing.JTextField l_valor1;
    private javax.swing.JButton libroregistrar;
    private javax.swing.JButton libroregistrar1;
    private javax.swing.JTabbedPane principal;
    private javax.swing.JRadioButton rb_accion;
    private javax.swing.JRadioButton rb_fantasia;
    private javax.swing.JRadioButton rb_historia;
    private javax.swing.JRadioButton rb_romance;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_eliminar;
    private javax.swing.JTextField tf_nuevacontra;
    private javax.swing.JTextField tf_nuevotel;
    private javax.swing.JTextField tf_nuevousuario;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JPanel tp_administar;
    private javax.swing.JPanel tp_ingreso;
    private javax.swing.JPanel tp_libros;
    private javax.swing.JPanel tp_registro;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuarios = new ArrayList();
    ArrayList<Libros> libros = new ArrayList();

}
